name: 5min-Notice-Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # 5분마다 실행
  workflow_dispatch:       # 수동 실행 버튼
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install requests playwright
          playwright install chromium

      - name: Run Bot
        run: python bot.py

      - name: Save Records
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 모든 last_...txt 파일(공지사항, 이벤트, 개발일지)을 추가
          git add last_*.txt || true
          
          if ! git diff --cached --quiet; then
            git commit -m "Update notices, events, and devlog"
            git push
          else
            echo "변경사항 없음"
          fi
